### ISSUE TITLE
Stopped working in 1.7.1

### ISSUE THREAD

**Issue by garyking** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#51]
I downgraded back to 1.5.23 since this extension stopped working in 1.7.1, released yesterday.

With the new version, the lightning icon doesn't appear in the status bar; when opening a workspace, the "cached stylesheets" message DOES briefly appear, though.

I also disabled all other extensions to test.

My settings:

```json
"html-css-class-completion.remoteStyleSheets": [
      "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css",
      "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
    ]
```

**Comment by gencer** [comment]
Do you have any logs in Developer Tools (Console)?

It will help me to debug as fast as possible.

**Comment by garyking** [comment]
I updated the original post for more accurate information

I've attached screenshots from `Toggle Developer Tools`.

Latest version (the one that isn't working):

![Latest version](https://user-images.githubusercontent.com/343940/80291032-00c38580-8718-11ea-9b0b-95bd55f4b007.png)

Latest working version:

![Latest working version](https://user-images.githubusercontent.com/343940/80291034-04efa300-8718-11ea-9066-19028e6d904e.png)

**Comment by gencer** [comment]
@garyking Just trying something from my end. Does this solve your problem?

# v1.7.2

[html-slim-scss-css-class-completion-1.7.2.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4534112/html-slim-scss-css-class-completion-1.7.2.zip)

**Comment by akmeghdad** [comment]
Hello,

Yes sir, v1.7.2 (html-slim-scss-css-class-completion-1.7.2.zip) solved my problem.

Thank you

**Comment by krupenja** [comment]
I think I was also getting this with 1.7.1. In my case, the extension was repeatedly crashing ExtensionHost and none of the other extensions were useable - disabling SCSS Everywhere
resolved this. With 1.7.2 and SCSS Everywhere enabled, I do not see this problem anymore 👍

**Comment by gencer** [comment]
@akmeghdad @krupenja @garyking 

Sorry foe the trouble. Glad it did worked. I just published **v1.7.2** on marketplace. Also changes are in `master`

Thank you for confirming guys! I really appreciated it.

One more time, sorry for the trouble I made with last release.

**Comment by gencer** [comment]
Closing this issue. Please let me know if something is not right again.

**Comment by garyking** [comment]
I'm sorry, but it's still not working for me. I currently have this extension **SCSS Everywhere** 1.7.2 installed, the latest. All other extensions disabled. I open a workspace with remote stylesheets, with the settings mentioned [here](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/issues/51#issue-606848201).

On workspace startup, I see the "Looking for CSS stylesheets" message briefly (about 0.1 seconds). In a React file, in the className attribute, I try typing a class name from Bootstrap. But no class suggestions appear, from this extension. 

Downgrading to the 1.5.23, once again, fixes the problem for me. Also, the "Looking for" message remains for much longer (about 5 seconds). Perhaps this is an issue with the new version not able to find remote stylesheets?

**Comment by gencer** [comment]
@garyking Do you use `searchRemoteGlobPattern` or just remote stylesheet as mentioned by you earlier?

**Comment by gencer** [comment]
Can you try **v1.7.3**?

[html-slim-scss-css-class-completion-1.7.3.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4535908/html-slim-scss-css-class-completion-1.7.3.zip)

**Comment by gencer** [comment]
# v1.7.4
Intensive debug information added:

Please try this version. This will enable debug logging which tagged as `SCSS-EVERYWHERE-DEBUG`. It will help me to understand where it get stuck.

[html-slim-scss-css-class-completion-1.7.4.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4535943/html-slim-scss-css-class-completion-1.7.4.zip)

**Comment by gencer** [comment]
# v1.7.4-2
Intensive debug information added.

Please try this version. This will enable debug logging which tagged as `SCSS-EVERYWHERE-DEBUG`. It will help me to understand where it get stuck.

[html-slim-scss-css-class-completion-1.7.4.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4535964/html-slim-scss-css-class-completion-1.7.4.zip)

**Comment by garyking** [comment]
I don't use the `searchRemoteGlobPattern` setting. It only exists in the 1.7 version, but I'm using the 1.5 version.

---

I installed the `v1.7.4-2` version. The problem is fixed in that version. I've also attached the logs, anyway.

![Screen Shot 2020-04-27 at 3 04 30 pm](https://user-images.githubusercontent.com/343940/80410671-f977b580-8898-11ea-9c53-c2fc7c84e208.png)

**Comment by gencer** [comment]
Glad it did worked. This is really a weird situation.

Hopefully will not break again.

Will publish on marketplace now.

Thanks! Let me know if help needed again. 

Can I close issue now? If everything is ok?

**Comment by garyking** [comment]
Yeah problem is fixed in 1.7.4, which I currently have installed.

Is it necessary to leave the debug messages in the extension?

**Comment by gencer** [comment]
Not necessarily. I will remove those debug messages in next version ;)

I just want to make sure nobody has the same issue again. So, will be removed in next.
